// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertLibrary(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertLibrary'](arg1, arg2, arg3);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}
