// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertLibrary(arg1:string,arg2:string,arg3:main.ConversionSettings):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;
